CREATE DATABASE Runners;

CREATE TABLE Runners (Runner_id BIGINT NOT NULL AUTO_INCREMENT, Name VARCHAR(120) NOT NULL, Time BIGINT NOT NULL, Penalty1 BIGINT NOT NULL, Penalty2 BIGINT NOT NULL, Points BIGINT, PRIMARY KEY (Runner_id)) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

INSERT INTO Runners VALUES (NULL, 'Michael', 123, 5, 2, NULL);
INSERT INTO Runners VALUES (NULL, 'Sarah', 83, 3, 3, NULL);
INSERT INTO Runners VALUES (NULL, 'John', 323, 1, 1, NULL);
INSERT INTO Runners VALUES (NULL, 'Ramon', 100, 8, 4, NULL);
INSERT INTO Runners VALUES (NULL, 'Andrew', 143, 4, 3, NULL);
INSERT INTO Runners VALUES (NULL, 'Antoine', 199, 3, 2, NULL);
INSERT INTO Runners VALUES (NULL, 'David', 101, 2, 1, NULL);
